### ISSUE TITLE
Support authentication

### ISSUE THREAD

**Issue by tstrul1** [HewlettPackard/Jenkins-stats#3]
Hi, it looks like i cant use this job whith jenkins that requires authentication... is there any way to support credentials?

**Comment by electrofelix** [comment]
One option would be to help port this to use python-jenkins from https://opendev.org/jjb/python-jenkins and add CLI options to pass username and password.

In the short term, I suspect you can probably embed a username + token into the server url as `https://<user>:<apitoken>@yourjenkins.url/`, it's not good security practice, but it should work as long as you're confident that the user/password isn't going to get exposed via referrer urls being sent somewhere else due to plugins in your jenkins instance.

**Comment by mulcahys** [comment]
@tstrul1 as @electrofelix responded, there isn't support yet but patches welcome.
